pkg-main: update 3 packages in azure-functions-python/debian-13/.azure-functions-python.inc.yaml (#90756)
* pkg-main: update azure-functions-templates-buildid

in package/main/azure-functions-python/debian-13/.azure-functions-python.inc.yaml

TEMPLATES_BUILDID:
 - 300127
 + 300562

* pkg-main: update azure-functions-templates-downloadurl

in package/main/azure-functions-python/debian-13/.azure-functions-python.inc.yaml

TEMPLATES_DOWNLOADURL:
 - https://artprodwus21.artifacts.visualstudio.com/Ad1c51fbc-4477-4a0f-b99f-fc9013009a58/ae7e3bf3-d41a-4480-9ac0-b6cf9df9ac24/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6ZnVuYy9wcm9qZWN0SWQvYWU3ZTNiZjMtZDQxYS00NDgwLTlhYzAtYjZjZjlkZjlhYzI0L2J1aWxkSWQvMzAwMTI3L2FydGlmYWN0TmFtZS9kcm9w0/content?format=zip
 + https://artprodwus21.artifacts.visualstudio.com/Ad1c51fbc-4477-4a0f-b99f-fc9013009a58/ae7e3bf3-d41a-4480-9ac0-b6cf9df9ac24/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6ZnVuYy9wcm9qZWN0SWQvYWU3ZTNiZjMtZDQxYS00NDgwLTlhYzAtYjZjZjlkZjlhYzI0L2J1aWxkSWQvMzAwNTYyL2FydGlmYWN0TmFtZS9kcm9w0/content?format=zip

* pkg-main: update Azure/azure-functions-extension-bundles

in package/main/azure-functions-python/debian-13/.azure-functions-python.inc.yaml

EXT_BUNDLE_VERSION:
 - 4.38.1
 + 4.39.0
EXT_BUNDLE_COMMIT_SHA:
 - 3c791acc9fa04ccd0979a697f8a8dd25ad3d22b6
 + 5009f1d2aa8153548dcf5673ac7202a523212a1d

* azure-functions-python: fix extension bundles nuget config path

Upstream 4.39.0 moved NuGet.config to the repo root and renamed the
Azure feed key; update the build step to patch the new layout while
keeping compatibility with older bundle tags.

---------

Co-authored-by: dhi-bot <dhi@docker.com>
Co-authored-by: dhi-bot <dhi@docker.com>

[dhi-commit=f3a1cca3b6e50cfbef25c81cdc35964d1c3fe75a]

diff --git a/package/main/azure-functions-python/debian-13/4-python3.12.yaml b/package/main/azure-functions-python/debian-13/4-python3.12.yaml
--- a/package/main/azure-functions-python/debian-13/4-python3.12.yaml
+++ b/package/main/azure-functions-python/debian-13/4-python3.12.yaml
@@ -4,9 +4,9 @@ image: dhi.io/pkg-azure-functions-python
 variant: runtime
 tags:
   - 4.1054.100
-  - 4.1054.100-r13
+  - 4.1054.100-r14
   - 4.1054.100-debian13
-  - 4.1054.100-r13-debian13
+  - 4.1054.100-r14-debian13
 platforms:
   - linux/amd64
 vars:
@@ -14,17 +14,17 @@ vars:
   COMMIT_SHA: d3dd29e5b076bef2c28a334f95e572ca0f039b64
   DOTNET_8_VERSION: 8.0.424-1
   DOTNET_10_VERSION: 10.0.400-1
-  EXT_BUNDLE_COMMIT_SHA: 3c791acc9fa04ccd0979a697f8a8dd25ad3d22b6
-  EXT_BUNDLE_VERSION: 4.38.1
+  EXT_BUNDLE_COMMIT_SHA: 5009f1d2aa8153548dcf5673ac7202a523212a1d
+  EXT_BUNDLE_VERSION: 4.39.0
   FUNCTIONS_WORKER: python
   PYTHON_MAJOR_MINOR_VERSION: "3.12"
   PYTHON_VERSION: 3.12.14-0
-  REL: "13"
+  REL: "14"
   SEMVER_MAJOR_MINOR_VERSION: "4.1054"
   SEMVER_MAJOR_VERSION: "4"
   SEMVER_VERSION: 4.1054.100
-  TEMPLATES_BUILDID: "300127"
-  TEMPLATES_DOWNLOADURL: https://artprodwus21.artifacts.visualstudio.com/Ad1c51fbc-4477-4a0f-b99f-fc9013009a58/ae7e3bf3-d41a-4480-9ac0-b6cf9df9ac24/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6ZnVuYy9wcm9qZWN0SWQvYWU3ZTNiZjMtZDQxYS00NDgwLTlhYzAtYjZjZjlkZjlhYzI0L2J1aWxkSWQvMzAwMTI3L2FydGlmYWN0TmFtZS9kcm9w0/content?format=zip
+  TEMPLATES_BUILDID: "300562"
+  TEMPLATES_DOWNLOADURL: https://artprodwus21.artifacts.visualstudio.com/Ad1c51fbc-4477-4a0f-b99f-fc9013009a58/ae7e3bf3-d41a-4480-9ac0-b6cf9df9ac24/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6ZnVuYy9wcm9qZWN0SWQvYWU3ZTNiZjMtZDQxYS00NDgwLTlhYzAtYjZjZjlkZjlhYzI0L2J1aWxkSWQvMzAwNTYyL2FydGlmYWN0TmFtZS9kcm9w0/content?format=zip
   VERSION: 4.1054.100
 contents:
   packages:
@@ -67,19 +67,19 @@ contents:
                   license: MIT
             uid: 0
             gid: 0
-          - url: git+https://github.com/Azure/azure-functions-extension-bundles.git#4.38.1
-            checksum: 3c791acc9fa04ccd0979a697f8a8dd25ad3d22b6
+          - url: git+https://github.com/Azure/azure-functions-extension-bundles.git#4.39.0
+            checksum: 5009f1d2aa8153548dcf5673ac7202a523212a1d
             path: ${source.dir}/azure-functions-extension-bundles
             spdx:
               name: azure-functions-extension-bundles
-              version: 4.38.1
+              version: 4.39.0
               packages:
                 - name: azure-functions-extension-bundles
-                  purl: pkg:github/Azure/azure-functions-extension-bundles@4.38.1
+                  purl: pkg:github/Azure/azure-functions-extension-bundles@4.39.0
                   license: MIT
             uid: 0
             gid: 0
-          - url: https://artprodwus21.artifacts.visualstudio.com/Ad1c51fbc-4477-4a0f-b99f-fc9013009a58/ae7e3bf3-d41a-4480-9ac0-b6cf9df9ac24/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6ZnVuYy9wcm9qZWN0SWQvYWU3ZTNiZjMtZDQxYS00NDgwLTlhYzAtYjZjZjlkZjlhYzI0L2J1aWxkSWQvMzAwMTI3L2FydGlmYWN0TmFtZS9kcm9w0/content?format=zip
+          - url: https://artprodwus21.artifacts.visualstudio.com/Ad1c51fbc-4477-4a0f-b99f-fc9013009a58/ae7e3bf3-d41a-4480-9ac0-b6cf9df9ac24/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2F6ZnVuYy9wcm9qZWN0SWQvYWU3ZTNiZjMtZDQxYS00NDgwLTlhYzAtYjZjZjlkZjlhYzI0L2J1aWxkSWQvMzAwNTYyL2FydGlmYWN0TmFtZS9kcm9w0/content?format=zip
             path: ${source.dir}/templatesArtifacts.zip
             uid: 0
             gid: 0
@@ -155,9 +155,20 @@ contents:
             export DOTNET_CLI_TELEMETRY_OPTOUT=1
             mkdir -p "${DOTNET_CLI_HOME}"
 
-            sed -E -i '${source.dir}/azure-functions-extension-bundles/src/Microsoft.Azure.Functions.ExtensionBundle/NuGet.Config' \
-              -e 's|azure-functions-extension-bundles|nuget.org|' \
-              -e 's|https://pkgs.dev.azure.com/[^"]+|https://api.nuget.org/v3/index.json|'
+            NUGET_CONFIG='${source.dir}/azure-functions-extension-bundles/NuGet.config'
+            LEGACY_NUGET_CONFIG='${source.dir}/azure-functions-extension-bundles/src/Microsoft.Azure.Functions.ExtensionBundle/NuGet.Config'
+            if [ -f "${NUGET_CONFIG}" ]; then
+              sed -E -i "${NUGET_CONFIG}" \
+                -e 's|upstream-public|nuget.org|g' \
+                -e 's|https://pkgs.dev.azure.com/[^"]+|https://api.nuget.org/v3/index.json|g'
+            elif [ -f "${LEGACY_NUGET_CONFIG}" ]; then
+              sed -E -i "${LEGACY_NUGET_CONFIG}" \
+                -e 's|azure-functions-extension-bundles|nuget.org|' \
+                -e 's|https://pkgs.dev.azure.com/[^"]+|https://api.nuget.org/v3/index.json|'
+            else
+              echo "NuGet config not found for extension bundles build" >&2
+              exit 1
+            fi
 
             TEMPLATES_ARTIFACTS_DIRECTORY=1 dotnet run \
               skip:GenerateVulnerabilityReport,PackageNetCoreV3BundlesWindows,CreateRUPackage,CreateCDNStoragePackage,CreateCDNStoragePackageWindows,BuildBundleBinariesForWindows
@@ -166,9 +177,9 @@ contents:
           runs: |
             set -eux -o pipefail
 
-            mkdir -p ${target.dir}/usr/share/FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.38.1
-            unzip Microsoft.Azure.Functions.ExtensionBundle.4.38.1_linux-x64.zip \
-              -d ${target.dir}/usr/share/FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.38.1
+            mkdir -p ${target.dir}/usr/share/FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.39.0
+            unzip Microsoft.Azure.Functions.ExtensionBundle.4.39.0_linux-x64.zip \
+              -d ${target.dir}/usr/share/FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.39.0
         - uses: dhi/build-pkg:0
           with:
             depends:
@@ -181,7 +192,7 @@ contents:
               - deb
             license: MIT
             name: azure-functions-python
-            rel: 13
+            rel: 14
             url: https://learn.microsoft.com/en-us/azure/azure-functions/functions-overview
             version: 4.1054.100
       paths:
