istio-proxyv2: update 2 packages in debian-13/1.29.yaml (#75337)
* istio-proxyv2: update istio/istio

in image/istio-proxyv2/debian-13/1.29.yaml

VERSION:
 - 1.29.5
 + 1.29.6
COMMIT_SHA:
 - fe1d6ad986110a26ad4e8b4044589f2b112daac1
 + 7019d6d3608e4995e9a36d2977cfec3a341431cd

* istio-proxyv2: update istio-proxy

in image/istio-proxyv2/debian-13/1.29.yaml

ISTIO_PROXY_SHA:
 - f1c35980fb70b3d27602932f4ee27f78990397b4
 + 8f4f69324c5c9271faad34c13e2e20a558669121

---------

Co-authored-by: dhi-bot <dhi@docker.com>

[dhi-commit=8e78e3e7e8e4d51aba8775ff513848808065e7b4]

diff --git a/image/istio-proxyv2/debian-13/1.29.yaml b/image/istio-proxyv2/debian-13/1.29.yaml
--- a/image/istio-proxyv2/debian-13/1.29.yaml
+++ b/image/istio-proxyv2/debian-13/1.29.yaml
@@ -5,11 +5,11 @@ image: dhi.io/istio-proxyv2
 variant: runtime
 tags:
   - "1.29"
-  - 1.29.5
+  - 1.29.6
   - 1.29-debian
   - 1.29-debian13
-  - 1.29.5-debian
-  - 1.29.5-debian13
+  - 1.29.6-debian
+  - 1.29.6-debian13
 platforms:
   - linux/amd64
   - linux/arm64
@@ -19,12 +19,12 @@ dates:
 vars:
   BAZEL_ARCH: '#{ target.arch == "amd64" ? "x86_64" : "arm64" }'
   BAZEL_VERSION: 7.7.1
-  COMMIT_SHA: fe1d6ad986110a26ad4e8b4044589f2b112daac1
-  ISTIO_PROXY_SHA: f1c35980fb70b3d27602932f4ee27f78990397b4
+  COMMIT_SHA: 7019d6d3608e4995e9a36d2977cfec3a341431cd
+  ISTIO_PROXY_SHA: 8f4f69324c5c9271faad34c13e2e20a558669121
   SEMVER_MAJOR_MINOR_VERSION: "1.29"
   SEMVER_MAJOR_VERSION: "1"
-  SEMVER_VERSION: 1.29.5
-  VERSION: 1.29.5
+  SEMVER_VERSION: 1.29.6
+  VERSION: 1.29.6
 contents:
   repositories:
     - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
@@ -78,27 +78,27 @@ contents:
           - findutils
           - gawk
         files:
-          - url: git+https://github.com/istio/istio.git#1.29.5
-            checksum: fe1d6ad986110a26ad4e8b4044589f2b112daac1
+          - url: git+https://github.com/istio/istio.git#1.29.6
+            checksum: 7019d6d3608e4995e9a36d2977cfec3a341431cd
             path: /go/src/istio.io/istio
             spdx:
               name: istio
-              version: 1.29.5
+              version: 1.29.6
               packages:
                 - name: istio
-                  purl: pkg:golang/istio.io/istio@1.29.5
+                  purl: pkg:golang/istio.io/istio@1.29.6
                   license: Apache-2.0
             uid: 0
             gid: 0
-          - url: git+https://github.com/istio/proxy.git#1.29.5
-            checksum: f1c35980fb70b3d27602932f4ee27f78990397b4
+          - url: git+https://github.com/istio/proxy.git#1.29.6
+            checksum: 8f4f69324c5c9271faad34c13e2e20a558669121
             path: ${source.dir}/istio-proxy
             spdx:
               name: istio-proxy
-              version: 1.29.5
+              version: 1.29.6
               packages:
                 - name: istio-proxy
-                  purl: pkg:golang/github.com/istio/proxy@1.29.5
+                  purl: pkg:golang/github.com/istio/proxy@1.29.6
                   license: Apache-2.0
             uid: 0
             gid: 0
@@ -116,8 +116,8 @@ contents:
             # Extract proxy SHA from istio.deps and validate against tracking
             proxy_sha=$(jq -r '.[] | select(.name == "PROXY_REPO_SHA") | .lastStableSHA' "/go/src/istio.io/istio/istio.deps")
 
-            if [ "$proxy_sha" != 'f1c35980fb70b3d27602932f4ee27f78990397b4' ]; then
-              echo "ERROR: ISTIO_PROXY_SHA mismatch: f1c35980fb70b3d27602932f4ee27f78990397b4 (def) / $proxy_sha (istio.deps)" >&2
+            if [ "$proxy_sha" != '8f4f69324c5c9271faad34c13e2e20a558669121' ]; then
+              echo "ERROR: ISTIO_PROXY_SHA mismatch: 8f4f69324c5c9271faad34c13e2e20a558669121 (def) / $proxy_sha (istio.deps)" >&2
               exit 1
             fi
         - name: update go dependencies (1.29 only)
@@ -444,16 +444,16 @@ contents:
               --override_repository=intel_dlb=/src/dlb-stub
               --@envoy//contrib/dlb/source:enabled=false
             "
-            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.29.5 > /opt/docker/sbom/envoy/.spdx.envoy.json
+            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.29.6 > /opt/docker/sbom/envoy/.spdx.envoy.json
         - name: build-pilot-agent
           privileged: true
           runs: |
             set -eux -o pipefail
 
-            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.29.5
-                       -X istio.io/istio/pkg/version.buildGitRevision=fe1d6ad986110a26ad4e8b4044589f2b112daac1
+            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.29.6
+                       -X istio.io/istio/pkg/version.buildGitRevision=7019d6d3608e4995e9a36d2977cfec3a341431cd
                        -X istio.io/istio/pkg/version.buildStatus=Clean
-                       -X istio.io/istio/pkg/version.buildTag=1.29.5
+                       -X istio.io/istio/pkg/version.buildTag=1.29.6
                        -X istio.io/istio/pkg/version.buildHub=docker.io/dhi
                        -X istio.io/istio/pkg/version.buildOS=$(go env GOOS)
                        -X istio.io/istio/pkg/version.buildArch=$(go env GOARCH)"
@@ -521,7 +521,7 @@ os-release:
   home-url: https://docker.com/products/hardened-images/
   bug-report-url: https://docker.com/support/
 environment:
-  ISTIO_META_ISTIO_PROXY_SHA: f1c35980fb70b3d27602932f4ee27f78990397b4
+  ISTIO_META_ISTIO_PROXY_SHA: 8f4f69324c5c9271faad34c13e2e20a558669121
 paths:
   - type: symlink
     path: /usr/sbin/iptables
