istio-proxyv2: update 2 packages in debian-13/1.30.yaml (#102334)
* istio-proxyv2: update istio/istio

in image/istio-proxyv2/debian-13/1.30.yaml

VERSION:
 - 1.30.4
 + 1.30.5
COMMIT_SHA:
 - 4220640be99e4cad69652d9eb2010bc5257f6a8e
 + 55b832fad2bc55f47e658b68cd1a7abf9540dbc9

* istio-proxyv2: update istio-proxy

in image/istio-proxyv2/debian-13/1.30.yaml

ISTIO_PROXY_SHA:
 - ce177c56fe75661f16b654e2f164d4ab02058222
 + 3bf722f59561ef9747835e543c0b648eb4ab1237

---------

Co-authored-by: dhi-bot <dhi@docker.com>

[dhi-commit=4caf7ac3be0d5d818e55dd9d67d00245b9412582]

diff --git a/image/istio-proxyv2/debian-13/1.30.yaml b/image/istio-proxyv2/debian-13/1.30.yaml
--- a/image/istio-proxyv2/debian-13/1.30.yaml
+++ b/image/istio-proxyv2/debian-13/1.30.yaml
@@ -5,11 +5,11 @@ image: dhi.io/istio-proxyv2
 variant: runtime
 tags:
   - "1.30"
-  - 1.30.4
+  - 1.30.5
   - 1.30-debian
   - 1.30-debian13
-  - 1.30.4-debian
-  - 1.30.4-debian13
+  - 1.30.5-debian
+  - 1.30.5-debian13
 platforms:
   - linux/amd64
   - linux/arm64
@@ -18,12 +18,12 @@ dates:
 vars:
   BAZEL_ARCH: '#{ target.arch == "amd64" ? "x86_64" : "arm64" }'
   BAZEL_VERSION: 7.7.1
-  COMMIT_SHA: 4220640be99e4cad69652d9eb2010bc5257f6a8e
-  ISTIO_PROXY_SHA: ce177c56fe75661f16b654e2f164d4ab02058222
+  COMMIT_SHA: 55b832fad2bc55f47e658b68cd1a7abf9540dbc9
+  ISTIO_PROXY_SHA: 3bf722f59561ef9747835e543c0b648eb4ab1237
   SEMVER_MAJOR_MINOR_VERSION: "1.30"
   SEMVER_MAJOR_VERSION: "1"
-  SEMVER_VERSION: 1.30.4
-  VERSION: 1.30.4
+  SEMVER_VERSION: 1.30.5
+  VERSION: 1.30.5
 contents:
   repositories:
     - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
@@ -77,27 +77,27 @@ contents:
           - findutils
           - gawk
         files:
-          - url: git+https://github.com/istio/istio.git#1.30.4
-            checksum: 4220640be99e4cad69652d9eb2010bc5257f6a8e
+          - url: git+https://github.com/istio/istio.git#1.30.5
+            checksum: 55b832fad2bc55f47e658b68cd1a7abf9540dbc9
             path: /go/src/istio.io/istio
             spdx:
               name: istio
-              version: 1.30.4
+              version: 1.30.5
               packages:
                 - name: istio
-                  purl: pkg:golang/istio.io/istio@1.30.4
+                  purl: pkg:golang/istio.io/istio@1.30.5
                   license: Apache-2.0
             uid: 0
             gid: 0
-          - url: git+https://github.com/istio/proxy.git#1.30.4
-            checksum: ce177c56fe75661f16b654e2f164d4ab02058222
+          - url: git+https://github.com/istio/proxy.git#1.30.5
+            checksum: 3bf722f59561ef9747835e543c0b648eb4ab1237
             path: ${source.dir}/istio-proxy
             spdx:
               name: istio-proxy
-              version: 1.30.4
+              version: 1.30.5
               packages:
                 - name: istio-proxy
-                  purl: pkg:golang/github.com/istio/proxy@1.30.4
+                  purl: pkg:golang/github.com/istio/proxy@1.30.5
                   license: Apache-2.0
             uid: 0
             gid: 0
@@ -115,8 +115,8 @@ contents:
             # Extract proxy SHA from istio.deps and validate against tracking
             proxy_sha=$(jq -r '.[] | select(.name == "PROXY_REPO_SHA") | .lastStableSHA' "/go/src/istio.io/istio/istio.deps")
 
-            if [ "$proxy_sha" != 'ce177c56fe75661f16b654e2f164d4ab02058222' ]; then
-              echo "ERROR: ISTIO_PROXY_SHA mismatch: ce177c56fe75661f16b654e2f164d4ab02058222 (def) / $proxy_sha (istio.deps)" >&2
+            if [ "$proxy_sha" != '3bf722f59561ef9747835e543c0b648eb4ab1237' ]; then
+              echo "ERROR: ISTIO_PROXY_SHA mismatch: 3bf722f59561ef9747835e543c0b648eb4ab1237 (def) / $proxy_sha (istio.deps)" >&2
               exit 1
             fi
         - name: update go dependencies (1.30 only)
@@ -445,16 +445,16 @@ contents:
               --override_repository=intel_dlb=/src/dlb-stub
               --@envoy//contrib/dlb/source:enabled=false
             "
-            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.30.4 > /opt/docker/sbom/envoy/.spdx.envoy.json
+            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.30.5 > /opt/docker/sbom/envoy/.spdx.envoy.json
         - name: build-pilot-agent
           privileged: true
           runs: |
             set -eux -o pipefail
 
-            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.30.4
-                       -X istio.io/istio/pkg/version.buildGitRevision=4220640be99e4cad69652d9eb2010bc5257f6a8e
+            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.30.5
+                       -X istio.io/istio/pkg/version.buildGitRevision=55b832fad2bc55f47e658b68cd1a7abf9540dbc9
                        -X istio.io/istio/pkg/version.buildStatus=Clean
-                       -X istio.io/istio/pkg/version.buildTag=1.30.4
+                       -X istio.io/istio/pkg/version.buildTag=1.30.5
                        -X istio.io/istio/pkg/version.buildHub=docker.io/dhi
                        -X istio.io/istio/pkg/version.buildOS=$(go env GOOS)
                        -X istio.io/istio/pkg/version.buildArch=$(go env GOARCH)"
@@ -522,7 +522,7 @@ os-release:
   home-url: https://docker.com/products/hardened-images/
   bug-report-url: https://docker.com/support/
 environment:
-  ISTIO_META_ISTIO_PROXY_SHA: ce177c56fe75661f16b654e2f164d4ab02058222
+  ISTIO_META_ISTIO_PROXY_SHA: 3bf722f59561ef9747835e543c0b648eb4ab1237
 paths:
   - type: symlink
     path: /usr/sbin/iptables
