istio-proxyv2: update 2 packages in debian-13/1.30.yaml (#91682)
* istio-proxyv2: update istio/istio

in image/istio-proxyv2/debian-13/1.30.yaml

VERSION:
 - 1.30.3
 + 1.30.4
COMMIT_SHA:
 - 56df41f63e513f834c9a3af33d8aed82d1d961f2
 + 4220640be99e4cad69652d9eb2010bc5257f6a8e

istio-proxyv2: update istio-proxy

in image/istio-proxyv2/debian-13/1.30.yaml

ISTIO_PROXY_SHA:
 - 81864a1cd5099d2f9e1289bfc604f4b200b2b27c
 + ce177c56fe75661f16b654e2f164d4ab02058222

* istio-proxyv2: remove obsolete bump entries

---------

Co-authored-by: dhi-bot <dhi@docker.com>

[dhi-commit=e81d13e48e96b2cd736a04eb988b2703aa5a0433]

diff --git a/image/istio-proxyv2/debian-13/1.30-dev.yaml b/image/istio-proxyv2/debian-13/1.30-dev.yaml
--- a/image/istio-proxyv2/debian-13/1.30-dev.yaml
+++ b/image/istio-proxyv2/debian-13/1.30-dev.yaml
@@ -6,13 +6,13 @@ variant: dev
 tags:
   - 1-dev
   - 1.30-dev
-  - 1.30.3-dev
+  - 1.30.4-dev
   - 1-debian-dev
   - 1-debian13-dev
   - 1.30-debian-dev
   - 1.30-debian13-dev
-  - 1.30.3-debian-dev
-  - 1.30.3-debian13-dev
+  - 1.30.4-debian-dev
+  - 1.30.4-debian13-dev
 platforms:
   - linux/amd64
   - linux/arm64
@@ -21,12 +21,12 @@ dates:
 vars:
   BAZEL_ARCH: '#{ target.arch == "amd64" ? "x86_64" : "arm64" }'
   BAZEL_VERSION: 7.7.1
-  COMMIT_SHA: 56df41f63e513f834c9a3af33d8aed82d1d961f2
-  ISTIO_PROXY_SHA: 81864a1cd5099d2f9e1289bfc604f4b200b2b27c
+  COMMIT_SHA: 4220640be99e4cad69652d9eb2010bc5257f6a8e
+  ISTIO_PROXY_SHA: ce177c56fe75661f16b654e2f164d4ab02058222
   SEMVER_MAJOR_MINOR_VERSION: "1.30"
   SEMVER_MAJOR_VERSION: "1"
-  SEMVER_VERSION: 1.30.3
-  VERSION: 1.30.3
+  SEMVER_VERSION: 1.30.4
+  VERSION: 1.30.4
 contents:
   repositories:
     - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
@@ -96,27 +96,27 @@ contents:
           - findutils
           - gawk
         files:
-          - url: git+https://github.com/istio/istio.git#1.30.3
-            checksum: 56df41f63e513f834c9a3af33d8aed82d1d961f2
+          - url: git+https://github.com/istio/istio.git#1.30.4
+            checksum: 4220640be99e4cad69652d9eb2010bc5257f6a8e
             path: /go/src/istio.io/istio
             spdx:
               name: istio
-              version: 1.30.3
+              version: 1.30.4
               packages:
                 - name: istio
-                  purl: pkg:golang/istio.io/istio@1.30.3
+                  purl: pkg:golang/istio.io/istio@1.30.4
                   license: Apache-2.0
             uid: 0
             gid: 0
-          - url: git+https://github.com/istio/proxy.git#1.30.3
-            checksum: 81864a1cd5099d2f9e1289bfc604f4b200b2b27c
+          - url: git+https://github.com/istio/proxy.git#1.30.4
+            checksum: ce177c56fe75661f16b654e2f164d4ab02058222
             path: ${source.dir}/istio-proxy
             spdx:
               name: istio-proxy
-              version: 1.30.3
+              version: 1.30.4
               packages:
                 - name: istio-proxy
-                  purl: pkg:golang/github.com/istio/proxy@1.30.3
+                  purl: pkg:golang/github.com/istio/proxy@1.30.4
                   license: Apache-2.0
             uid: 0
             gid: 0
@@ -134,15 +134,14 @@ contents:
             # Extract proxy SHA from istio.deps and validate against tracking
             proxy_sha=$(jq -r '.[] | select(.name == "PROXY_REPO_SHA") | .lastStableSHA' "/go/src/istio.io/istio/istio.deps")
 
-            if [ "$proxy_sha" != '81864a1cd5099d2f9e1289bfc604f4b200b2b27c' ]; then
-              echo "ERROR: ISTIO_PROXY_SHA mismatch: 81864a1cd5099d2f9e1289bfc604f4b200b2b27c (def) / $proxy_sha (istio.deps)" >&2
+            if [ "$proxy_sha" != 'ce177c56fe75661f16b654e2f164d4ab02058222' ]; then
+              echo "ERROR: ISTIO_PROXY_SHA mismatch: ce177c56fe75661f16b654e2f164d4ab02058222 (def) / $proxy_sha (istio.deps)" >&2
               exit 1
             fi
         - name: update go dependencies (1.30 only)
           uses: go/bump@v1
           with:
-            deps:
-              - google.golang.org/grpc@v1.82.1
+            deps: []
             dir: /go/src/istio.io/istio
             download: true
         - name: patch-afero-bazel-deps
@@ -463,16 +462,16 @@ contents:
               --override_repository=intel_dlb=/src/dlb-stub
               --@envoy//contrib/dlb/source:enabled=false
             "
-            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.30.3 > /opt/docker/sbom/envoy/.spdx.envoy.json
+            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.30.4 > /opt/docker/sbom/envoy/.spdx.envoy.json
         - name: build-pilot-agent
           privileged: true
           runs: |
             set -eux -o pipefail
 
-            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.30.3
-                       -X istio.io/istio/pkg/version.buildGitRevision=56df41f63e513f834c9a3af33d8aed82d1d961f2
+            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.30.4
+                       -X istio.io/istio/pkg/version.buildGitRevision=4220640be99e4cad69652d9eb2010bc5257f6a8e
                        -X istio.io/istio/pkg/version.buildStatus=Clean
-                       -X istio.io/istio/pkg/version.buildTag=1.30.3
+                       -X istio.io/istio/pkg/version.buildTag=1.30.4
                        -X istio.io/istio/pkg/version.buildHub=docker.io/dhi
                        -X istio.io/istio/pkg/version.buildOS=$(go env GOOS)
                        -X istio.io/istio/pkg/version.buildArch=$(go env GOARCH)"
@@ -545,7 +544,7 @@ os-release:
   bug-report-url: https://docker.com/support/
 environment:
   DEBIAN_FRONTEND: noninteractive
-  ISTIO_META_ISTIO_PROXY_SHA: 81864a1cd5099d2f9e1289bfc604f4b200b2b27c
+  ISTIO_META_ISTIO_PROXY_SHA: ce177c56fe75661f16b654e2f164d4ab02058222
 paths:
   - type: symlink
     path: /usr/sbin/iptables
