istio-proxyv2: update 2 packages in debian-13/1.31.yaml (#102139)
* istio-proxyv2: update istio/istio

in image/istio-proxyv2/debian-13/1.31.yaml

VERSION:
 - 1.31.0
 + 1.31.1
COMMIT_SHA:
 - eed52ebb66ade45214088877b0f82855d954060d
 + 190ae921b848ec010b8be4457533837ed8fce258

* istio-proxyv2: update istio-proxy

in image/istio-proxyv2/debian-13/1.31.yaml

ISTIO_PROXY_SHA:
 - 0a12a02f0db52f6d229ec0fbe0f2091e1c02098b
 + 3bb16354647d089b9a79020c9fc86cbbc5fcf84b

---------

Co-authored-by: dhi-bot <dhi@docker.com>

[dhi-commit=f4ef77ce3eab8c8c2b7fa57f0057e9fcbcf7abb4]

diff --git a/image/istio-proxyv2/debian-13/1.31-dev.yaml b/image/istio-proxyv2/debian-13/1.31-dev.yaml
--- a/image/istio-proxyv2/debian-13/1.31-dev.yaml
+++ b/image/istio-proxyv2/debian-13/1.31-dev.yaml
@@ -6,13 +6,13 @@ variant: dev
 tags:
   - 1-dev
   - 1.31-dev
-  - 1.31.0-dev
+  - 1.31.1-dev
   - 1-debian-dev
   - 1-debian13-dev
   - 1.31-debian-dev
   - 1.31-debian13-dev
-  - 1.31.0-debian-dev
-  - 1.31.0-debian13-dev
+  - 1.31.1-debian-dev
+  - 1.31.1-debian13-dev
 platforms:
   - linux/amd64
   - linux/arm64
@@ -22,12 +22,12 @@ dates:
 vars:
   BAZEL_ARCH: '#{ target.arch == "amd64" ? "x86_64" : "arm64" }'
   BAZEL_VERSION: 8.7.0
-  COMMIT_SHA: eed52ebb66ade45214088877b0f82855d954060d
-  ISTIO_PROXY_SHA: 0a12a02f0db52f6d229ec0fbe0f2091e1c02098b
+  COMMIT_SHA: 190ae921b848ec010b8be4457533837ed8fce258
+  ISTIO_PROXY_SHA: 3bb16354647d089b9a79020c9fc86cbbc5fcf84b
   SEMVER_MAJOR_MINOR_VERSION: "1.31"
   SEMVER_MAJOR_VERSION: "1"
-  SEMVER_VERSION: 1.31.0
-  VERSION: 1.31.0
+  SEMVER_VERSION: 1.31.1
+  VERSION: 1.31.1
 contents:
   repositories:
     - deb [signed-by=/usr/share/keyrings/dhi-deb-main.gpg] http://dhi.io/deb/debian/main trixie main
@@ -97,27 +97,27 @@ contents:
           - findutils
           - gawk
         files:
-          - url: git+https://github.com/istio/istio.git#1.31.0
-            checksum: eed52ebb66ade45214088877b0f82855d954060d
+          - url: git+https://github.com/istio/istio.git#1.31.1
+            checksum: 190ae921b848ec010b8be4457533837ed8fce258
             path: /go/src/istio.io/istio
             spdx:
               name: istio
-              version: 1.31.0
+              version: 1.31.1
               packages:
                 - name: istio
-                  purl: pkg:golang/istio.io/istio@1.31.0
+                  purl: pkg:golang/istio.io/istio@1.31.1
                   license: Apache-2.0
             uid: 0
             gid: 0
-          - url: git+https://github.com/istio/proxy.git#1.31.0
-            checksum: 0a12a02f0db52f6d229ec0fbe0f2091e1c02098b
+          - url: git+https://github.com/istio/proxy.git#1.31.1
+            checksum: 3bb16354647d089b9a79020c9fc86cbbc5fcf84b
             path: ${source.dir}/istio-proxy
             spdx:
               name: istio-proxy
-              version: 1.31.0
+              version: 1.31.1
               packages:
                 - name: istio-proxy
-                  purl: pkg:golang/github.com/istio/proxy@1.31.0
+                  purl: pkg:golang/github.com/istio/proxy@1.31.1
                   license: Apache-2.0
             uid: 0
             gid: 0
@@ -135,8 +135,8 @@ contents:
             # Extract proxy SHA from istio.deps and validate against tracking
             proxy_sha=$(jq -r '.[] | select(.name == "PROXY_REPO_SHA") | .lastStableSHA' "/go/src/istio.io/istio/istio.deps")
 
-            if [ "$proxy_sha" != '0a12a02f0db52f6d229ec0fbe0f2091e1c02098b' ]; then
-              echo "ERROR: ISTIO_PROXY_SHA mismatch: 0a12a02f0db52f6d229ec0fbe0f2091e1c02098b (def) / $proxy_sha (istio.deps)" >&2
+            if [ "$proxy_sha" != '3bb16354647d089b9a79020c9fc86cbbc5fcf84b' ]; then
+              echo "ERROR: ISTIO_PROXY_SHA mismatch: 3bb16354647d089b9a79020c9fc86cbbc5fcf84b (def) / $proxy_sha (istio.deps)" >&2
               exit 1
             fi
         - name: update go dependencies (1.31 only)
@@ -467,16 +467,16 @@ contents:
               --override_repository=intel_dlb=/src/dlb-stub
               --@envoy//contrib/dlb/source:enabled=false
             "
-            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.31.0 > /opt/docker/sbom/envoy/.spdx.envoy.json
+            python ${source.dir}/bin/envoy-bazel-to-spdx.py istio-proxyv2-envoy 1.31.1 > /opt/docker/sbom/envoy/.spdx.envoy.json
         - name: build-pilot-agent
           privileged: true
           runs: |
             set -eux -o pipefail
 
-            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.31.0
-                       -X istio.io/istio/pkg/version.buildGitRevision=eed52ebb66ade45214088877b0f82855d954060d
+            GOLDFLAGS="-X istio.io/istio/pkg/version.buildVersion=1.31.1
+                       -X istio.io/istio/pkg/version.buildGitRevision=190ae921b848ec010b8be4457533837ed8fce258
                        -X istio.io/istio/pkg/version.buildStatus=Clean
-                       -X istio.io/istio/pkg/version.buildTag=1.31.0
+                       -X istio.io/istio/pkg/version.buildTag=1.31.1
                        -X istio.io/istio/pkg/version.buildHub=docker.io/dhi
                        -X istio.io/istio/pkg/version.buildOS=$(go env GOOS)
                        -X istio.io/istio/pkg/version.buildArch=$(go env GOARCH)"
@@ -549,7 +549,7 @@ os-release:
   bug-report-url: https://docker.com/support/
 environment:
   DEBIAN_FRONTEND: noninteractive
-  ISTIO_META_ISTIO_PROXY_SHA: 0a12a02f0db52f6d229ec0fbe0f2091e1c02098b
+  ISTIO_META_ISTIO_PROXY_SHA: 3bb16354647d089b9a79020c9fc86cbbc5fcf84b
 paths:
   - type: symlink
     path: /usr/sbin/iptables
