opensearch: fix cves (#86466)
* opensearch: fix cves

* opensearch: fix patchesç

* opensearch: add new patch

[dhi-commit=63ee931b762baec0b78c874c4c1321b98dc9e033]

diff --git a/image/opensearch/debian-13/3.yaml b/image/opensearch/debian-13/3.yaml
--- a/image/opensearch/debian-13/3.yaml
+++ b/image/opensearch/debian-13/3.yaml
@@ -44,7 +44,7 @@ vars:
   INDEX_MANAGEMENT_COMMIT_SHA: 592e20171db2d385c67abf3e4c48bcf1555c6e3c
   INDEX_MANAGEMENT_VERSION: 3.8.0.0
   JACKSON_ANNOTATIONS_PATCH_VERSION: "2.22"
-  JACKSON_PATCH_VERSION: 2.22.0
+  JACKSON_PATCH_VERSION: 2.22.1
   JAVA_FIPS_SUFFIX: ""
   JAVA_VARIANT: jre
   JDK_MAJOR_VERSION: "21"
@@ -54,7 +54,7 @@ vars:
   K_NN_VERSION: 3.8.0.0
   ML_COMMONS_COMMIT_SHA: 694e8cb9565da1439fbe26e3c9339bde2be56c09
   ML_COMMONS_VERSION: 3.8.0.0
-  NETTY_PATCH_VERSION: 4.2.16.Final
+  NETTY_PATCH_VERSION: 4.2.17.Final
   NEURAL_SEARCH_COMMIT_SHA: fc733c807f12cb40db890ba15e584046cd6a3c1b
   NEURAL_SEARCH_VERSION: 3.8.0.0
   NOTIFICATIONS_COMMIT_SHA: e6f8fa966fcd5f6ba43f60b180df91e3f9e03771
@@ -474,68 +474,68 @@ contents:
             path: ${source.dir}/opensearch-build
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-buffer/4.2.16.Final/netty-buffer-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-buffer-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-buffer/4.2.17.Final/netty-buffer-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-buffer-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec/4.2.16.Final/netty-codec-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-codec-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec/4.2.17.Final/netty-codec-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-codec-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec-http/4.2.16.Final/netty-codec-http-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-codec-http-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec-http/4.2.17.Final/netty-codec-http-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-codec-http-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec-http2/4.2.16.Final/netty-codec-http2-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-codec-http2-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec-http2/4.2.17.Final/netty-codec-http2-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-codec-http2-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec-http3/4.2.16.Final/netty-codec-http3-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-codec-http3-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec-http3/4.2.17.Final/netty-codec-http3-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-codec-http3-4.2.17.Final.jar
             uid: 1000
             gid: 1000
           - url: https://maven-central.storage-download.googleapis.com/maven2/com/fasterxml/jackson/core/jackson-annotations/2.22/jackson-annotations-2.22.jar
             path: ${source.dir}/patch/deps/jackson-annotations-2.22.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/com/fasterxml/jackson/core/jackson-databind/2.22.0/jackson-databind-2.22.0.jar
-            path: ${source.dir}/patch/deps/jackson-databind-2.22.0.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/com/fasterxml/jackson/core/jackson-databind/2.22.1/jackson-databind-2.22.1.jar
+            path: ${source.dir}/patch/deps/jackson-databind-2.22.1.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.22.0/jackson-datatype-jsr310-2.22.0.jar
-            path: ${source.dir}/patch/deps/jackson-datatype-jsr310-2.22.0.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.22.1/jackson-datatype-jsr310-2.22.1.jar
+            path: ${source.dir}/patch/deps/jackson-datatype-jsr310-2.22.1.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/com/fasterxml/jackson/module/jackson-module-afterburner/2.22.0/jackson-module-afterburner-2.22.0.jar
-            path: ${source.dir}/patch/deps/jackson-module-afterburner-2.22.0.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/com/fasterxml/jackson/module/jackson-module-afterburner/2.22.1/jackson-module-afterburner-2.22.1.jar
+            path: ${source.dir}/patch/deps/jackson-module-afterburner-2.22.1.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec-classes-quic/4.2.16.Final/netty-codec-classes-quic-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-codec-classes-quic-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-codec-classes-quic/4.2.17.Final/netty-codec-classes-quic-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-codec-classes-quic-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-common/4.2.16.Final/netty-common-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-common-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-common/4.2.17.Final/netty-common-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-common-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-handler/4.2.16.Final/netty-handler-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-handler-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-handler/4.2.17.Final/netty-handler-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-handler-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-resolver/4.2.16.Final/netty-resolver-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-resolver-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-resolver/4.2.17.Final/netty-resolver-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-resolver-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-transport/4.2.16.Final/netty-transport-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-transport-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-transport/4.2.17.Final/netty-transport-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-transport-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-transport-classes-epoll/4.2.16.Final/netty-transport-classes-epoll-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-transport-classes-epoll-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-transport-classes-epoll/4.2.17.Final/netty-transport-classes-epoll-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-transport-classes-epoll-4.2.17.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-transport-native-unix-common/4.2.16.Final/netty-transport-native-unix-common-4.2.16.Final.jar
-            path: ${source.dir}/patch/deps/netty-transport-native-unix-common-4.2.16.Final.jar
+          - url: https://maven-central.storage-download.googleapis.com/maven2/io/netty/netty-transport-native-unix-common/4.2.17.Final/netty-transport-native-unix-common-4.2.17.Final.jar
+            path: ${source.dir}/patch/deps/netty-transport-native-unix-common-4.2.17.Final.jar
             uid: 1000
             gid: 1000
       pipeline:
@@ -553,6 +553,11 @@ contents:
           work-dir: ${source.dir}/OpenSearch
           with:
             patch: ${source.dir}/patch/buildsrc-maven-mirror.patch
+        - name: patch OpenSearch HttpComponents catalog versions
+          uses: git/patch@v1
+          work-dir: ${source.dir}/OpenSearch
+          with:
+            patch: ${source.dir}/patch/libs-versions-httpcomponents.patch
         - name: patch OpenSearch IDE Gradle Maven mirror
           uses: git/patch@v1
           work-dir: ${source.dir}/OpenSearch
@@ -751,11 +756,11 @@ contents:
 
             if [[ -n "${bundled_netty_ver}" ]]; then
               # Compare versions (simple lexicographic comparison is good enough for now)
-              if [[ "${bundled_netty_ver}" > "4.2.16.Final" ]] || [[ "${bundled_netty_ver}" = "4.2.16.Final" ]]; then
-                echo "ERROR: Bundled Netty version ${bundled_netty_ver} is >= target version 4.2.16.Final" >&2
+              if [[ "${bundled_netty_ver}" > "4.2.17.Final" ]] || [[ "${bundled_netty_ver}" = "4.2.17.Final" ]]; then
+                echo "ERROR: Bundled Netty version ${bundled_netty_ver} is >= target version 4.2.17.Final" >&2
                 exit 1
               fi
-              echo "Bundled version ${bundled_netty_ver} < target 4.2.16.Final, proceeding with upgrade..."
+              echo "Bundled version ${bundled_netty_ver} < target 4.2.17.Final, proceeding with upgrade..."
             else
               echo "WARNING: Found netty classes but could not determine version, proceeding..."
             fi
@@ -767,9 +772,9 @@ contents:
               exit 1
             fi
 
-            echo "Bundling netty 4.2.16.Final jars..."
+            echo "Bundling netty 4.2.17.Final jars..."
             for netty_dep in netty-buffer netty-codec netty-codec-http netty-codec-http2 netty-codec-http3 netty-codec-classes-quic netty-common netty-handler netty-resolver netty-transport netty-transport-classes-epoll netty-transport-native-unix-common; do
-              cp ${source.dir}/patch/deps/${netty_dep}-4.2.16.Final.jar .
+              cp ${source.dir}/patch/deps/${netty_dep}-4.2.17.Final.jar .
             done
 
             echo "Checking bundled Jackson in ${sa_commons_jar}..."
@@ -778,11 +783,11 @@ contents:
             else
               bundled_jackson_databind_ver="$(unzip -p "${sa_commons_jar}" 'META-INF/maven/com.fasterxml.jackson.core/jackson-databind/pom.properties' 2> /dev/null | grep '^version=' | cut -d= -f2 || echo "")"
               if [[ -n "${bundled_jackson_databind_ver}" ]]; then
-                if [[ "${bundled_jackson_databind_ver}" > "2.22.0" ]] || [[ "${bundled_jackson_databind_ver}" = "2.22.0" ]]; then
-                  echo "ERROR: Bundled jackson-databind version ${bundled_jackson_databind_ver} is >= target version 2.22.0" >&2
+                if [[ "${bundled_jackson_databind_ver}" > "2.22.1" ]] || [[ "${bundled_jackson_databind_ver}" = "2.22.1" ]]; then
+                  echo "ERROR: Bundled jackson-databind version ${bundled_jackson_databind_ver} is >= target version 2.22.1" >&2
                   exit 1
                 fi
-                echo "Bundled jackson-databind ${bundled_jackson_databind_ver} < target 2.22.0, proceeding with upgrade..."
+                echo "Bundled jackson-databind ${bundled_jackson_databind_ver} < target 2.22.1, proceeding with upgrade..."
               else
                 echo "WARNING: Found Jackson classes but could not determine jackson-databind version, proceeding..."
               fi
@@ -798,10 +803,10 @@ contents:
                 exit 1
               fi
 
-              echo "Bundling Jackson 2.22.0 jars not already provided by OpenSearch core..."
+              echo "Bundling Jackson 2.22.1 jars not already provided by OpenSearch core..."
               cp ${source.dir}/patch/deps/jackson-annotations-2.22.jar .
               for jackson_dep in jackson-databind jackson-datatype-jsr310 jackson-module-afterburner; do
-                cp ${source.dir}/patch/deps/${jackson_dep}-2.22.0.jar .
+                cp ${source.dir}/patch/deps/${jackson_dep}-2.22.1.jar .
               done
             fi
         - name: copy config and entrypoint files
@@ -831,6 +836,12 @@ contents:
           gid: 0
           mode: "0444"
           source: image/opensearch/patch/buildsrc-maven-mirror.patch
+        - type: file
+          path: /src/patch/libs-versions-httpcomponents.patch
+          uid: 0
+          gid: 0
+          mode: "0444"
+          source: image/opensearch/patch/libs-versions-httpcomponents.patch
         - type: file
           path: /src/patch/ide-gradle-maven-mirror.patch
           uid: 0
