opensearch: remediate cves with gradle init script and dhi-gradle (#51112)
Replace brittle build.gradle and toml sed overrides with a versioned
init script and /usr/local/bin/dhi-gradle wrapper. Add opensearch
bc-fips VEX for CVE-2026-8149 while no fixed Maven coordinate exists.

[dhi-commit=04f5fe406466ce0907b11de3581f2884cbc5e264]

diff --git a/image/opensearch/debian-13/3.yaml b/image/opensearch/debian-13/3.yaml
--- a/image/opensearch/debian-13/3.yaml
+++ b/image/opensearch/debian-13/3.yaml
@@ -51,7 +51,7 @@ vars:
   K_NN_VERSION: 3.6.0.0
   ML_COMMONS_COMMIT_SHA: 4f7054ff02c2476e2307220c47af07e899120644
   ML_COMMONS_VERSION: 3.6.0.0
-  NETTY_PATCH_VERSION: 4.2.11.Final
+  NETTY_PATCH_VERSION: 4.2.13.Final
   NEURAL_SEARCH_COMMIT_SHA: 84943265eda028ef7554813abec77e4029dab4d5
   NEURAL_SEARCH_VERSION: 3.6.0.0
   NOTIFICATIONS_COMMIT_SHA: 1929b1cf1d6b05d830b58916a8d1d6182f2f5ad8
@@ -463,47 +463,54 @@ contents:
             path: ${source.dir}/opensearch-build
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-buffer/4.2.11.Final/netty-buffer-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-buffer-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-buffer/4.2.13.Final/netty-buffer-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-buffer-4.2.13.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-codec/4.2.11.Final/netty-codec-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-codec-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-codec/4.2.13.Final/netty-codec-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-codec-4.2.13.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-codec-http/4.2.11.Final/netty-codec-http-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-codec-http-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-codec-http/4.2.13.Final/netty-codec-http-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-codec-http-4.2.13.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-codec-http2/4.2.11.Final/netty-codec-http2-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-codec-http2-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-codec-http2/4.2.13.Final/netty-codec-http2-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-codec-http2-4.2.13.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-common/4.2.11.Final/netty-common-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-common-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-common/4.2.13.Final/netty-common-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-common-4.2.13.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-handler/4.2.11.Final/netty-handler-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-handler-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-handler/4.2.13.Final/netty-handler-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-handler-4.2.13.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-resolver/4.2.11.Final/netty-resolver-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-resolver-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-resolver/4.2.13.Final/netty-resolver-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-resolver-4.2.13.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-transport/4.2.11.Final/netty-transport-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-transport-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-transport/4.2.13.Final/netty-transport-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-transport-4.2.13.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-transport-classes-epoll/4.2.11.Final/netty-transport-classes-epoll-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-transport-classes-epoll-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-transport-classes-epoll/4.2.13.Final/netty-transport-classes-epoll-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-transport-classes-epoll-4.2.13.Final.jar
             uid: 1000
             gid: 1000
-          - url: https://repo1.maven.org/maven2/io/netty/netty-transport-native-unix-common/4.2.11.Final/netty-transport-native-unix-common-4.2.11.Final.jar
-            path: ${source.dir}/patch/deps/netty-transport-native-unix-common-4.2.11.Final.jar
+          - url: https://repo1.maven.org/maven2/io/netty/netty-transport-native-unix-common/4.2.13.Final/netty-transport-native-unix-common-4.2.13.Final.jar
+            path: ${source.dir}/patch/deps/netty-transport-native-unix-common-4.2.13.Final.jar
             uid: 1000
             gid: 1000
       pipeline:
+        - name: stage DHI Gradle CVE overrides init script
+          work-dir: ${source.dir}
+          runs: |
+            set -eux -o pipefail
+
+            cp "${source.dir}/patch/3.6.overrides.gradle" \
+              "${source.dir}/dhi-overrides.init.gradle"
         - name: patch security plugin
           uses: git/patch@v1
           work-dir: ${source.dir}/security
@@ -525,8 +532,8 @@ contents:
           runs: |
             set -eux -o pipefail
 
-            gradle publishToMavenLocal -Dbuild.snapshot=false -Dopensearch.version=3.6.0
-            gradle :build-tools:publishToMavenLocal -Dbuild.snapshot=false -Dopensearch.version=3.6.0
+            dhi-gradle publishToMavenLocal -Dbuild.snapshot=false -Dopensearch.version=3.6.0
+            dhi-gradle :build-tools:publishToMavenLocal -Dbuild.snapshot=false -Dopensearch.version=3.6.0
 
             # Then create the distribution
             # Non-FIPS needs -Pcrypto.standard=FIPS-140-3 to include bc-fips JARs in lib/
@@ -537,7 +544,7 @@ contents:
             if [ "${target.fips}" != "true" ]; then
               FIPS_GRADLE_FLAG="-Pcrypto.standard=FIPS-140-3"
             fi
-            gradle localDistro -Dbuild.snapshot=false -Dopensearch.version=3.6.0 ${FIPS_GRADLE_FLAG}
+            dhi-gradle localDistro -Dbuild.snapshot=false -Dopensearch.version=3.6.0 ${FIPS_GRADLE_FLAG}
 
             # Remove the bundled jdk
             rm -r "${source.dir}/OpenSearch/build/distribution/local/opensearch-3.6.0/jdk"
@@ -547,16 +554,16 @@ contents:
           runs: |
             set -eux -o pipefail
 
-            gradle build -Dbuild.snapshot=false -Dopensearch.version=3.6.0
-            gradle publishToMavenLocal -Dbuild.snapshot=false -Dopensearch.version=3.6.0
+            dhi-gradle build -Dbuild.snapshot=false -Dopensearch.version=3.6.0
+            dhi-gradle publishToMavenLocal -Dbuild.snapshot=false -Dopensearch.version=3.6.0
         - name: build opensearch-remote-metadata-sdk
           work-dir: ${source.dir}/opensearch-remote-metadata-sdk
           privileged: true
           runs: |
             set -eux -o pipefail
 
-            gradle build -Dbuild.snapshot=false -Dopensearch.version=3.6.0
-            gradle publishToMavenLocal -Dbuild.snapshot=false -Dopensearch.version=3.6.0
+            dhi-gradle build -Dbuild.snapshot=false -Dopensearch.version=3.6.0
+            dhi-gradle publishToMavenLocal -Dbuild.snapshot=false -Dopensearch.version=3.6.0
         - name: build plugins
           privileged: true
           runs: |
@@ -600,7 +607,7 @@ contents:
 
             for plugindir in "${plugins[@]}"; do
               cd ${source.dir}/${plugindir}
-              gradle assemble -Dbuild.snapshot=false -Dopensearch.version=3.6.0 ${FIPS_GRADLE_FLAG}
+              dhi-gradle assemble -Dbuild.snapshot=false -Dopensearch.version=3.6.0 ${FIPS_GRADLE_FLAG}
             done
         - name: assemble opensearch distribution
           runs: |
@@ -681,11 +688,11 @@ contents:
 
             if [[ -n "${bundled_netty_ver}" ]]; then
               # Compare versions (simple lexicographic comparison is good enough for now)
-              if [[ "${bundled_netty_ver}" > "4.2.11.Final" ]] || [[ "${bundled_netty_ver}" = "4.2.11.Final" ]]; then
-                echo "ERROR: Bundled Netty version ${bundled_netty_ver} is >= target version 4.2.11.Final" >&2
+              if [[ "${bundled_netty_ver}" > "4.2.13.Final" ]] || [[ "${bundled_netty_ver}" = "4.2.13.Final" ]]; then
+                echo "ERROR: Bundled Netty version ${bundled_netty_ver} is >= target version 4.2.13.Final" >&2
                 exit 1
               fi
-              echo "Bundled version ${bundled_netty_ver} < target 4.2.11.Final, proceeding with upgrade..."
+              echo "Bundled version ${bundled_netty_ver} < target 4.2.13.Final, proceeding with upgrade..."
             else
               echo "WARNING: Found netty classes but could not determine version, proceeding..."
             fi
@@ -697,9 +704,9 @@ contents:
               exit 1
             fi
 
-            echo "Bundling netty 4.2.11.Final jars..."
+            echo "Bundling netty 4.2.13.Final jars..."
             for netty_dep in netty-buffer netty-codec netty-codec-http netty-codec-http2 netty-common netty-handler netty-resolver netty-transport netty-transport-classes-epoll netty-transport-native-unix-common; do
-              cp ${source.dir}/patch/deps/${netty_dep}-4.2.11.Final.jar .
+              cp ${source.dir}/patch/deps/${netty_dep}-4.2.13.Final.jar .
             done
         - name: copy config and entrypoint files
           runs: |
@@ -710,6 +717,18 @@ contents:
             cp "${source.dir}/opensearch-build/config/opensearch.yml" "${target.dir}/opensearch/config/opensearch.yml"
             cp "${source.dir}/opensearch-build/docker/release/config/opensearch/log4j2.properties" "${target.dir}/opensearch/config/log4j2.properties"
       paths:
+        - type: file
+          path: /usr/local/bin/dhi-gradle
+          uid: 0
+          gid: 0
+          mode: "0555"
+          source: image/opensearch/scripts/dhi-gradle.sh
+        - type: file
+          path: ${source.dir}/patch/3.6.overrides.gradle
+          uid: 0
+          gid: 0
+          mode: "0444"
+          source: image/opensearch/patch/3.6.overrides.gradle
         - type: file
           path: /src/patch/plugin-security.patch
           uid: 0
