gitlab-rails: drop gem build headers and static libs (#109071)
Co-authored-by: gwsiimpl

Co-authored-by: dhi-bot <dhi@docker.com>

[dhi-commit=a113a0fd6cba636fda4c657416728ad1b7ad232c]

diff --git a/package/main/gitlab-rails/debian-13/19.yaml b/package/main/gitlab-rails/debian-13/19.yaml
--- a/package/main/gitlab-rails/debian-13/19.yaml
+++ b/package/main/gitlab-rails/debian-13/19.yaml
@@ -3,37 +3,37 @@
 image: dhi.io/pkg-gitlab-rails
 variant: runtime
 tags:
-  - 19.1.8
-  - 19.1.8-r2
-  - 19.1.8-debian13
-  - 19.1.8-r2-debian13
+  - 19.4.1
+  - 19.4.1-r0
+  - 19.4.1-debian13
+  - 19.4.1-r0-debian13
 platforms:
   - linux/amd64
   - linux/arm64
 dates:
-  release: "2026-09-10"
+  release: "2026-09-22"
 vars:
-  COMMIT_SHA: 25601e798604a50f025102e4598a6884305802c4
+  COMMIT_SHA: 191678a37648bc14466c2bed346ed60eee7ddec6
   COREPACK_VERSION: 0.36.0-0
-  DEVFILE_COMMIT_SHA: 8a4dc1fa50f1c799536bd0779c4cb96336f11ff8
-  DEVFILE_OUT: /srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.2-${MACHINE_ARCH}-linux/out
-  DEVFILE_VERSION: 0.5.2
+  DEVFILE_COMMIT_SHA: 30640cb427fa7850cb9cd8c13d3f3fa1fc5734a1
+  DEVFILE_OUT: /srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.4-${MACHINE_ARCH}-linux/out
+  DEVFILE_VERSION: 0.5.4
   DOCUTILS_VERSION: "0.19"
   GOLANG_MAJOR_MINOR_VERSION: "1.27"
-  GOLANG_VERSION: 1.27.1-0
+  GOLANG_VERSION: 1.27.1-1
   MACHINE_ARCH: '#{ target.arch == "amd64" ? "x86_64" : "aarch64" }'
-  NODEJS_VERSION: 22.23.2-1
-  NPM_VERSION: 11.19.1-0
+  NODEJS_VERSION: 22.23.3-0
+  NPM_VERSION: 11.20.0-0
   PACKAGE_NAME: gitlab-rails-19
   PYTHON_MAJOR_MINOR_VERSION: "3.12"
-  PYTHON_VERSION: 3.12.14-1
-  REL: "2"
+  PYTHON_VERSION: 3.12.15-0
+  REL: "0"
   RUBY_MAJOR_MINOR_VERSION: "3.3"
-  RUBY_VERSION: 3.3.12-50
-  SEMVER_MAJOR_MINOR_VERSION: "19.1"
+  RUBY_VERSION: 3.3.12-67
+  SEMVER_MAJOR_MINOR_VERSION: "19.4"
   SEMVER_MAJOR_VERSION: "19"
-  SEMVER_VERSION: 19.1.8
-  VERSION: 19.1.8
+  SEMVER_VERSION: 19.4.1
+  VERSION: 19.4.1
   YARN_VERSION: 1.22.22-1
 contents:
   repositories:
@@ -47,8 +47,8 @@ contents:
       work-dir: /srv/gitlab
       contents:
         packages:
-          - ruby-3.3=3.3.12-50
-          - ruby-3.3-dev=3.3.12-50
+          - ruby-3.3=3.3.12-67
+          - ruby-3.3-dev=3.3.12-67
           - libffi8
           - libgmp10
           - libjemalloc-dev
@@ -59,13 +59,13 @@ contents:
           - libyaml-0-2
           - libyaml-dev
           - zlib1g
-          - python-3.12=3.12.14-1
-          - python-3.12-dev=3.12.14-1
-          - python-3.12-minimal=3.12.14-1
-          - libpython-3.12=3.12.14-1
-          - libpython-3.12-dev=3.12.14-1
-          - libpython-3.12-minimal=3.12.14-1
-          - libpython-3.12-stdlib=3.12.14-1
+          - python-3.12=3.12.15-0
+          - python-3.12-dev=3.12.15-0
+          - python-3.12-minimal=3.12.15-0
+          - libpython-3.12=3.12.15-0
+          - libpython-3.12-dev=3.12.15-0
+          - libpython-3.12-minimal=3.12.15-0
+          - libpython-3.12-stdlib=3.12.15-0
           - python3-pip-whl
           - python3-setuptools-whl
           - python3-wheel
@@ -131,34 +131,34 @@ contents:
           - patch
           - pkg-config
           - sudo
-          - nodejs-22=22.23.2-1
-          - npm=11.19.1-0
+          - nodejs-22=22.23.3-0
+          - npm=11.20.0-0
           - node-corepack=0.36.0-0
           - yarn-classic=1.22.22-1
-          - golang-1.27=1.27.1-0
-          - golang-1.27-oci-config=1.27.1-0
+          - golang-1.27=1.27.1-1
+          - golang-1.27-oci-config=1.27.1-1
         files:
-          - url: git+https://gitlab.com/gitlab-org/gitlab-foss.git#v19.1.8
-            checksum: 25601e798604a50f025102e4598a6884305802c4
+          - url: git+https://gitlab.com/gitlab-org/gitlab-foss.git#v19.4.1
+            checksum: 191678a37648bc14466c2bed346ed60eee7ddec6
             path: /srv/gitlab
             spdx:
               name: gitlab-ce
-              version: 19.1.8
+              version: 19.4.1
               packages:
                 - name: gitlab-ce
-                  purl: pkg:gitlab/gitlab-org/gitlab-foss@v19.1.8
+                  purl: pkg:gitlab/gitlab-org/gitlab-foss@v19.4.1
                   license: MIT AND CC-BY-SA-4.0
             uid: 0
             gid: 0
-          - url: git+https://gitlab.com/gitlab-org/ruby/gems/devfile-gem.git#0.5.2
-            checksum: 8a4dc1fa50f1c799536bd0779c4cb96336f11ff8
+          - url: git+https://gitlab.com/gitlab-org/ruby/gems/devfile-gem.git#0.5.4
+            checksum: 30640cb427fa7850cb9cd8c13d3f3fa1fc5734a1
             path: /go/src/devfile-gem
             spdx:
               name: devfile-gem
-              version: 0.5.2
+              version: 0.5.4
               packages:
                 - name: devfile-gem
-                  purl: pkg:golang/gitlab-org/ruby/gems/devfile-gem@0.5.2
+                  purl: pkg:golang/gitlab-org/ruby/gems/devfile-gem@0.5.4
                   license: MIT
             uid: 0
             gid: 0
@@ -182,7 +182,7 @@ contents:
 
             export BUNDLE_JOBS=1
 
-            bundle lock --update activestorage activesupport actionview actionpack railties addressable faraday net-imap nokogiri sidekiq-cron graphql puma concurrent-ruby websocket-driver excon css_parser loofah rails-html-sanitizer json msgpack oauth2 ruby-lsp prawn-svg sys-filesystem --conservative
+            bundle lock --update activestorage activesupport actionview actionpack railties addressable faraday net-imap nokogiri sidekiq-cron puma concurrent-ruby websocket-driver excon css_parser loofah rails-html-sanitizer json msgpack oauth2 ruby-lsp prawn-svg sys-filesystem --conservative
 
             echo "Lockfile updated:"
             grep -E "activestorage|addressable|^    faraday |^    net-imap |^    nokogiri |^    sidekiq-cron |^    graphql |^    puma |^    concurrent-ruby |^    websocket-driver |^    excon |^    css_parser |^    loofah |^    rails-html-sanitizer |^    json |^    msgpack |^    oauth2 |^    ruby-lsp |^    prawn-svg " Gemfile.lock | head -32 || true
@@ -308,10 +308,7 @@ contents:
             rm -rf ${RUBY_DIR}/*/extensions/*/*/*/mkmf.log \
               ${RUBY_DIR}/*/extensions/*/*/*/gem_make.out
 
-            rm -rf ${RUBY_DIR}/*/gems/*/ext/*.c \
-              ${RUBY_DIR}/*/gems/*/ext/*/*.c \
-              ${RUBY_DIR}/*/gems/*/ext/*.o \
-              ${RUBY_DIR}/*/gems/*/ext/*/*.o
+            find ${RUBY_DIR}/*/gems -type f \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.o' -o -name '*.h' -o -name '*.hpp' -o -name '*.a' \) -delete
 
             rm -rf ${RUBY_DIR}/*/gems/*/*.gemspec \
               ${RUBY_DIR}/*/gems/*/*.md \
@@ -367,7 +364,7 @@ contents:
               - github.com/cloudflare/circl@v1.6.4
               - github.com/go-git/go-git/v5@v5.19.2
               - google.golang.org/grpc@v1.85.0-dev.0.20260825072537-93e31b48545e
-              - github.com/containerd/containerd@v1.7.35
+              - github.com/containerd/containerd@v1.7.36
             download: true
         - name: test devfile
           work-dir: /go/src/devfile-gem/ext
@@ -384,19 +381,19 @@ contents:
           runs: |
             set -eux -o pipefail
 
-            test -d "/srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.2-${MACHINE_ARCH}-linux/out" || {
-              echo "devfile gem dir not found: /srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.2-${MACHINE_ARCH}-linux/out"
+            test -d "/srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.4-${MACHINE_ARCH}-linux/out" || {
+              echo "devfile gem dir not found: /srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.4-${MACHINE_ARCH}-linux/out"
               exit 1
             }
-            rm -f "/srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.2-${MACHINE_ARCH}-linux/out"/devfile-*-linux
-            rm -rf "/srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.2-${MACHINE_ARCH}-linux/out/../ext"
+            rm -f "/srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.4-${MACHINE_ARCH}-linux/out"/devfile-*-linux
+            rm -rf "/srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.4-${MACHINE_ARCH}-linux/out/../ext"
         - name: build devfile binary
           uses: go/build@v1
           work-dir: /go/src/devfile-gem/ext
           with:
             cgo_enabled: 0
             fips: false
-            output: /srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.2-${MACHINE_ARCH}-linux/out/devfile-${target.arch}-linux
+            output: /srv/gitlab/vendor/bundle/ruby/3.3.0/gems/devfile-0.5.4-${MACHINE_ARCH}-linux/out/devfile-${target.arch}-linux
             packages: .
         - name: stage package payload
           runs: |
@@ -448,9 +445,9 @@ contents:
               - deb
             license: MIT AND CC-BY-SA-4.0
             name: gitlab-rails-19
-            rel: 2
+            rel: 0
             url: https://gitlab.com/gitlab-org/gitlab-foss
-            version: 19.1.8
+            version: 19.4.1
       paths:
         - type: file
           path: ${source.dir}/patch/gem-constraints-19.patch
